stages:
  - lint
  - build
  - doc
  - deploy
  - sdk

before_script:
  # CCache Config
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_COMPILERCHECK=content
  - export CCACHE_MAXSIZE=32G
  - export CCACHE_COMPRESS=1
  - export CCACHE_SLOPPINESS=include_file_ctime,pch_defines,time_macros
  - export CCACHE_NOHASHDIR=1
  - git config --global http.sslVerify "false"


sheldon-mr:
  image: ${DOCKER_ENVDEV_MINT19}
  stage: lint
  script:
    - export ORIG_BRANCH_COMMIT_SHA=$(git merge-base dev origin/${CI_COMMIT_REF_NAME})
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@git.ircad.fr/Sight/sight-git.git -b dev
    # Execute sheldon, on all commits from the merge request
    - sight-git/hooks/sheldon ${ORIG_BRANCH_COMMIT_SHA}..${CI_COMMIT_SHA}

sheldon:
  image: ${DOCKER_ENVDEV_MINT19}
  stage: lint
  script:
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@git.ircad.fr/Sight/sight-git.git -b dev
    - sight-git/hooks/sheldon HEAD^ HEAD
  except:
    - dev
    - master

build:debug-linux:
  image: ${DOCKER_ENVDEV_MINT19}
  stage: build
  script:
    - export CCACHE_DIR=/cache/ccache
    - export CC=/usr/local/lib/ccache/clang
    - export CXX=/usr/local/lib/ccache/clang++
    - mkdir $CI_PROJECT_DIR/install $CI_PROJECT_DIR/build
    - cd $CI_PROJECT_DIR/build/
    - ccache -s
    - >
     cmake $CI_PROJECT_DIR
     -G Ninja
     -DUSE_CONAN=ON
     -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/install
     -DCMAKE_BUILD_TYPE=Debug
     -DBUILD_TESTS=ON
     -DBUILD_DOCUMENTATION=OFF
     -DENABLE_PCH=ON
    - ninja
    - ccache -s

build:release-linux:
  image: ${DOCKER_ENVDEV_MINT19}
  stage: build
  variables:
    CONAN_USER_HOME: $CI_PROJECT_DIR/conan
  script:
    - export CCACHE_DIR=/cache/ccache
    - export CC=/usr/local/lib/ccache/clang
    - export CXX=/usr/local/lib/ccache/clang++
    - mkdir $CI_PROJECT_DIR/install $CI_PROJECT_DIR/build
    - cd $CI_PROJECT_DIR/build/
    - ccache -s
    - >
     cmake $CI_PROJECT_DIR
     -G Ninja
     -DUSE_CONAN=ON
     -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/install
     -DCMAKE_BUILD_TYPE=Release
     -DBUILD_TESTS=ON
     -DBUILD_DOCUMENTATION=OFF
     -DENABLE_PCH=ON
    - ninja
    - ccache -s

doxygen:
  image: ${DOCKER_ENVDEV_MINT19}
  stage: doc
  script:
    - sudo apt-get update -yqq && sudo apt-get install -yqq graphviz doxygen
    - export CC=/usr/bin/clang-6.0
    - export CXX=/usr/bin/clang++-6.0
    - mkdir $CI_PROJECT_DIR/install $CI_PROJECT_DIR/build
    - cd $CI_PROJECT_DIR/build/
    - >
     cmake $CI_PROJECT_DIR
     -G Ninja
     -DUSE_CONAN=ON
     -DCMAKE_INSTALL_PREFIX=$CI_PROJECT_DIR/install
     -DCMAKE_BUILD_TYPE=Release
     -DBUILD_TESTS=OFF
     -DBUILD_DOCUMENTATION=ON
     -DENABLE_PCH=ON
    - ninja doc
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - $CI_PROJECT_DIR/build/Documentation/Doxygen/

pages:
  image: ${DOCKER_ENVDEV_MINT19}
  stage: deploy
  dependencies:
    - doxygen
  script:
    - mv build/Documentation/Doxygen/html/ public/
  artifacts:
    paths:
    - public
  only:
    - dev
    
sdk:
  image: ${DOCKER_ENVDEV_MINT19}
  stage: build
  when : manual
  script:
    - export SDK_PATH=${HOME}/sdk
    - export SDK_BUILD_PATH=${SDK_PATH}/build
    - export SDK_INSTALL_PATH=${SDK_PATH}/install
    - export CONAN_USER_HOME=${SDK_PATH}/conan
    - export CCACHE_DIR=/cache/ccache
    - export CC=/usr/local/lib/ccache/clang
    - export CXX=/usr/local/lib/ccache/clang++
    
    - mkdir -p ${SDK_BUILD_PATH} ${SDK_INSTALL_PATH}
    - cd ${SDK_BUILD_PATH}
    - ccache -s
    - >
     cmake ${CI_PROJECT_DIR}
     -G Ninja
     -DUSE_CONAN=ON
     -DCMAKE_INSTALL_PREFIX=${SDK_INSTALL_PATH}
     -DCMAKE_BUILD_TYPE=Release
     -DBUILD_TESTS=OFF
     -DBUILD_DOCUMENTATION=OFF
     -DENABLE_PCH=ON
     -DBUILD_SDK=ON
    - ninja
    - ninja install
    - find ${SDK_INSTALL_PATH}/lib/cmake/sight -type f
      -exec sed -i 's@/home/sight/[^;"]*/include@${_IMPORT_PREFIX}/include@g' {} \;
    - ninja package
    - ccache -s
    - export SDK_FILE_PATH=$(find ${HOME}/sdk/build/packages -maxdepth 1 -iname '*.tar.gz' -type f -print -quit) 
    - export SDK_FILE_NAME=$(basename ${SDK_FILE_PATH})
    - curl -u${CONAN_USERNAME}:${CONAN_PASSWORD} -T ${SDK_FILE_PATH} "https://conan.ircad.fr/artifactory/data/sdk/${SDK_FILE_NAME}"
    - mv packages/*.tar.gz ${CI_PROJECT_DIR}/
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/*.tar.gz
